Repository NYTimes/drone-gke, pull requests merged in 2018-06, with the labels that each got.

#84 Clarify local example
  README.md
  local-example/.kube.sec.yml
  local-example/.kube.yml
  local-example/vars.json
Labels: kind/doc

#89 update gcloud SDK to 206.0.0
  Dockerfile
Labels: version/0.4

#88 update gcloud SDK to 206.0.0
  Dockerfile
Labels: version/0.5+

#91 Use available base image
  Dockerfile.1.8
Labels: kind/fix
